packages:
  - "packages/**"

catalog:
  "@eslint/compat": ^1.1.1
  "@eslint/eslintrc": ^3.1.0
  "@eslint/js": ^9.10.0
  "@types/eslint__eslintrc": ^2.1.2
  "@types/eslint__js": ^8.42.3
  "@typescript-eslint/eslint-plugin": ^8.6.0
  "@typescript-eslint/parser": ^8.6.0
  arktype: 2.0.0-rc.5
  drizzle-orm: ^0.33.0
  effect: "^3.8.0"
  ofetch: "^1.3.4"
  ufo: ^1.5.4
  dotenv: ^16.4.5
  eslint: ^9.10.0
  globals: ^15.9.0
  jiti: 2.0.0-rc.1
  nitropack: ^2.9.7
  pathe: ^1.1.2
  prettier: ^3.3.3
  unbuild: ^2.0.0
