packages:
  - "packages/**"

catalog:
  "@effect/platform": ^0.66.2
  "@effect/platform-node": ^0.61.3
  "@effect/sql": ^0.14.0
  "@effect/sql-drizzle": 0.12.0
  "@effect/sql-pg": ^0.14.0
  "@eslint/compat": ^1.1.1
  "@eslint/eslintrc": ^3.1.0
  "@eslint/js": ^9.10.0
  "@types/eslint__eslintrc": ^2.1.2
  "@types/eslint__js": ^8.42.3
  "@typescript-eslint/eslint-plugin": ^8.6.0
  "@typescript-eslint/parser": ^8.6.0
  arktype: 2.0.0-rc.12
  drizzle-orm: ^0.33.0
  effect: ^3.8.4
  ofetch: ^1.4.0
  ufo: ^1.5.4
  dotenv: ^16.4.5
  eslint: ^9.10.0
  globals: ^15.9.0
  h3: ^1.12.0
  jiti: 2.0.0-rc.1
  jsonwebtoken: ^9.0.2
  nitropack: ^2.9.7
  pathe: ^1.1.2
  prettier: ^3.3.3
  unbuild: ^2.0.0
