packages:
  - "packages/**"

catalog:
  "@ark/util": ^0.35.0
  "@effect/experimental": ^0.39.1
  "@effect/platform": ^0.75.1
  "@effect/platform-node": ^0.71.1
  "@effect/schema": ^0.75.5
  "@effect/sql": ^0.28.1
  "@effect/sql-drizzle": 0.27.1
  "@effect/sql-pg": ^0.29.1
  "@eslint/compat": ^1.2.5
  "@eslint/eslintrc": ^3.2.0
  "@eslint/js": ^9.18.0
  "@types/eslint__eslintrc": ^2.1.2
  "@types/eslint__js": ^8.42.3
  "@types/jsonwebtoken": ^9.0.7
  "@typescript-eslint/eslint-plugin": ^8.21.0
  "@typescript-eslint/parser": ^8.21.0
  arktype: ^2.0.0
  c12: ^2.0.1
  destr: ^2.0.3
  drizzle-orm: ^0.38.4
  effect: ^3.12.7
  ofetch: ^1.4.1
  ufo: ^1.5.4
  dotenv: ^16.4.7
  eslint: ^9.18.0
  globals: ^15.14.0
  h3: ^1.14.0
  jiti: ^2.4.2
  jsonwebtoken: ^9.0.2
  nitropack: ^2.10.4
  pathe: ^2.0.2
  prettier: ^3.4.2
  vite: ^6.0.11
  vite-plugin-dts: ^4.5.0
  vitest: ^3.0.4
