apiVersion: apps/v1
kind: Deployment
metadata:
  name: sport-reservation-chat
  labels:
    app: sport-reservation-chat
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sport-reservation-chat
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: sport-reservation-chat
    spec:
      containers:
        - name: sport-reservation-chat
          image: <IMAGE>
          ports:
            - containerPort: 3000
              name: sp-chat-svc
          env:
            - name: SECRET_PATH
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-auth-secret
                  key: secretPath
            - name: POSTGRES_URL
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-chat-secret
                  key: postgresUrls
            - name: VALKEY_URL
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-chat-secret
                  key: valkeyUrl
            - name: KAFKA_BOOTSTRAP_URL
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-chat-secret
                  key: kafkaBootstrapUrl
            - name: KAFKA_SSL_KEY
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-auth-secret
                  key: kafkaSslKey
            - name: KAFKA_SSL_CERT
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-auth-secret
                  key: kafkaSslCert
            - name: KAFKA_SSL_CA
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-auth-secret
                  key: kafkaSslCa
            - name: UPLOAD_SECRET
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-chat-secret
                  key: uploadSecret
            - name: UPLOAD_BASE_URL
              valueFrom:
                secretKeyRef:
                  name: sport-reservation-chat-secret
                  key: uploadBaseUrls
          volumeMounts:
            - name: sport-reservation-auth-secret-path
              readOnly: true
              mountPath: "/.secret"
      volumes:
        - name: sport-reservation-auth-secret-path
          secret:
            secretName: sport-reservation-auth-secret-path

---
apiVersion: v1
kind: Service
metadata:
  name: sport-reservation-chat-service
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: sp-chat-svc
  selector:
    app: sport-reservation-chat
