// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/friend/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/friend/list.get').default>>>>
    }
    '/friend/remove': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/friend/remove.post').default>>>>
    }
    '/friend/request/accept': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/friend/request/accept.post').default>>>>
    }
    '/friend/request/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/friend/request/create.post').default>>>>
    }
    '/friend/request/list': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/friend/request/list.get').default>>>>
    }
    '/friend/request/reject': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/friend/request/reject.post').default>>>>
    }
    '/group/group': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/group/group.get').default>>>>
    }
    '/group/members': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/group/members.get').default>>>>
    }
    '/group/pending': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/group/pending.get').default>>>>
    }
    '/group/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/group/status.get').default>>>>
    }
    '/user/create': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user/create.post').default>>>>
    }
    '/user/profile': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user/profile.get').default>>>>
    }
    '/user/update': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/user/update.post').default>>>>
    }
  }
}
export {}