apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: sport-reservation-web-secret
    envs:
      - .env.secret
  - name: sport-reservation-web-secret-path
    files:
      - auth.key.pub
configMapGenerator:
generatorOptions:
  disableNameSuffixHash: true
resources:
