apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
secretGenerator:
  - name: sport-reservation-auth-secret
    envs:
      - .env.secret
  - name: sport-reservation-auth-secret-path
    files:
      - auth.key
configMapGenerator:
generatorOptions:
  disableNameSuffixHash: true
resources:
